name: Deploy

on:
  push:
    branches:
      - test-meowmeet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository 
        run: echo 'Checking out repository'
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku 
        run: echo 'Deploy to Heroku'
        
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-meowmeet"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "main"



